---
all:
  children:
    ru_relays:
      hosts:
        ru-msk-1:
          ansible_host: "{{ vault_ru_msk_1_ip }}"
          server_tag: ru-msk-1
          server_location: moscow
        ru-msk-2:
          ansible_host: "{{ vault_ru_msk_2_ip }}"
          server_tag: ru-msk-2
          server_location: moscow
        ru-msk-3:
          ansible_host: "{{ vault_ru_msk_3_ip }}"
          server_tag: ru-msk-3
          server_location: moscow
    foreign_exits:
      hosts:
        nl-ams-1:
          ansible_host: "{{ vault_nl_ams_1_ip }}"
          server_tag: nl-ams-1
          server_location: amsterdam
        nl-ams-2:
          ansible_host: "{{ vault_nl_ams_2_ip }}"
          server_tag: nl-ams-2
          server_location: amsterdam
        de-fra-1:
          ansible_host: "{{ vault_de_fra_1_ip }}"
          server_tag: de-fra-1
          server_location: frankfurt
    subscription:
      children:
        ru_relays: {}
    telegram_bot:
      hosts:
        nl-ams-1: {}
