---
foreign_servers:
  - tag: nl-ams-1
    address: "{{ vault_nl_ams_1_ip }}"
    port: 443
    location: amsterdam
  - tag: de-fra-1
    address: "{{ vault_de_fra_1_ip }}"
    port: 443
    location: frankfurt
  - tag: nl-ams-2
    address: "{{ vault_nl_ams_2_ip }}"
    port: 443
    location: amsterdam

ru_servers:
  - tag: ru-msk-1
    address: "{{ vault_ru_msk_1_ip }}"
    port: 443
    location: moscow
  - tag: ru-spb-1
    address: "{{ vault_ru_spb_1_ip }}"
    port: 443
    location: saint-petersburg
  - tag: ru-msk-3
    address: "{{ vault_ru_msk_3_ip }}"
    port: 443
    location: moscow
